on: [push]

name: build

jobs:
  check:
    name: Deploy
    runs-on: ubuntu-20.04-16core
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - run: zig version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-lambda
          version: latest
      - run: cargo lambda build --release
      - run: cargo lambda deploy

